name: GitHub Pages

on:
  push:
    branches: [ master ]
  schedule:
    # 06:00 UTC = 08:00 in NL (zomertijd).
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Fetch latest Laposta newsletter
        env:
          LAPOSTA_API_KEY: ${{ secrets.LAPOSTA_API_KEY }}
        run: node scripts/fetchLaposta.mjs

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --buildFuture --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public